apiVersion: v1
kind: Service
metadata:
  name: fitness-planner
  labels:
    app: fitness-planner
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: fitness-planner
