apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-planner
  labels:
    app: fitness-planner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-planner
  template:
    metadata:
      labels:
        app: fitness-planner
    spec:
      containers:
      - name: fitness-planner
        image: dnarlakanti/fitness-planner:7aef5c05faad88bf4f76f74e95e599c5b5d02ed8
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
